docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sy18
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sy18"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: [ "pgdata:/var/lib/postgresql/data" ]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: [.env]
    depends_on:
      db:
        condition: service_healthy
    ports: [ "8000:8000" ]

  web:
    build:
      context: ./web
      dockerfile: ../Dockerfile.frontend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    depends_on: [ backend ]
    ports: [ "3000:3000" ]

volumes:
  pgdata:
